name: Docker Build

on:
  push:
    tags:
      - '*/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          context: images/${{ env.IMAGE }}
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE }}:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE }}
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/images/${{ env.IMAGE }}/Dockerfile
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
          push: true
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/kaniko-cache
