name: Docker Build

on:
  push:
    tags:
      - '*/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Extract image name and version from tag
        run: |
          echo "IMAGE=$(echo ${{ github.ref_name }} | cut -d'/' -f1)" >> $GITHUB_ENV
          echo "VERSION=$(echo ${{ github.ref_name }} | cut -d'/' -f2)" >> $GITHUB_ENV
      - name: Debug
        run: |
          echo "Image: $IMAGE"
          echo "Version: $VERSION"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          context: images/${{ env.IMAGE }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE }}/${{ env.VERSION }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/kaniko-cache
