name: Docker Build

on:
  push:
    tags:
      - '*/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Extract image name and version from tag
        run: |
          echo "IMAGE=$(echo ${{ github.ref_name }} | cut -d'/' -f1)" >> $GITHUB_ENV
          echo "VERSION=$(echo ${{ github.ref_name }} | cut -d'/' -f2)" >> $GITHUB_ENV
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          #tags: |
          #  type=ref,event=tag
          #  type=sha
      - name: Debug metadata output
        run: |
          echo "Metadata outputs: ${{ toJson(steps.metadata.outputs.labels) }}"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          context: images/${{ env.IMAGE }}
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE }}:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE }}
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/images/${{ env.IMAGE }}/Dockerfile
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
          push: true
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/kaniko-cache
